// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/acl/group/delete_group.go
//
// Generated by this command:
//
//	Cursor-0.48.8-x86_64.AppImage -source=internal/usecase/acl/group/delete_group.go -destination=internal/usecase/acl/group/mock/mock_delete_group_repo.go -package=group_mock
//

// Package group_mock is a generated GoMock package.
package group_mock

import (
	reflect "reflect"

	acl "github.com/jekiapp/topic-master/internal/model/acl"
	gomock "go.uber.org/mock/gomock"
)

// MockiDeleteGroupRepo is a mock of iDeleteGroupRepo interface.
type MockiDeleteGroupRepo struct {
	ctrl     *gomock.Controller
	recorder *MockiDeleteGroupRepoMockRecorder
}

// MockiDeleteGroupRepoMockRecorder is the mock recorder for MockiDeleteGroupRepo.
type MockiDeleteGroupRepoMockRecorder struct {
	mock *MockiDeleteGroupRepo
}

// NewMockiDeleteGroupRepo creates a new mock instance.
func NewMockiDeleteGroupRepo(ctrl *gomock.Controller) *MockiDeleteGroupRepo {
	mock := &MockiDeleteGroupRepo{ctrl: ctrl}
	mock.recorder = &MockiDeleteGroupRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockiDeleteGroupRepo) EXPECT() *MockiDeleteGroupRepoMockRecorder {
	return m.recorder
}

// DeleteGroupByID mocks base method.
func (m *MockiDeleteGroupRepo) DeleteGroupByID(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroupByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroupByID indicates an expected call of DeleteGroupByID.
func (mr *MockiDeleteGroupRepoMockRecorder) DeleteGroupByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroupByID", reflect.TypeOf((*MockiDeleteGroupRepo)(nil).DeleteGroupByID), id)
}

// GetGroupByID mocks base method.
func (m *MockiDeleteGroupRepo) GetGroupByID(id string) (acl.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByID", id)
	ret0, _ := ret[0].(acl.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByID indicates an expected call of GetGroupByID.
func (mr *MockiDeleteGroupRepoMockRecorder) GetGroupByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByID", reflect.TypeOf((*MockiDeleteGroupRepo)(nil).GetGroupByID), id)
}
