// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/jekiapp/topic-master/internal/usecase/acl/auth (interfaces: ISignupRepo)
//
// Generated by this command:
//
//	mockgen -destination signup_mock.go -package mock github.com/jekiapp/topic-master/internal/usecase/acl/auth ISignupRepo
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	acl "github.com/jekiapp/topic-master/internal/model/acl"
	gomock "go.uber.org/mock/gomock"
)

// MockISignupRepo is a mock of ISignupRepo interface.
type MockISignupRepo struct {
	ctrl     *gomock.Controller
	recorder *MockISignupRepoMockRecorder
}

// MockISignupRepoMockRecorder is the mock recorder for MockISignupRepo.
type MockISignupRepoMockRecorder struct {
	mock *MockISignupRepo
}

// NewMockISignupRepo creates a new mock instance.
func NewMockISignupRepo(ctrl *gomock.Controller) *MockISignupRepo {
	mock := &MockISignupRepo{ctrl: ctrl}
	mock.recorder = &MockISignupRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISignupRepo) EXPECT() *MockISignupRepoMockRecorder {
	return m.recorder
}

// CreateApplication mocks base method.
func (m *MockISignupRepo) CreateApplication(arg0 acl.Application) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApplication", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateApplication indicates an expected call of CreateApplication.
func (mr *MockISignupRepoMockRecorder) CreateApplication(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApplication", reflect.TypeOf((*MockISignupRepo)(nil).CreateApplication), arg0)
}

// CreateApplicationAssignment mocks base method.
func (m *MockISignupRepo) CreateApplicationAssignment(arg0 acl.ApplicationAssignment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApplicationAssignment", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateApplicationAssignment indicates an expected call of CreateApplicationAssignment.
func (mr *MockISignupRepoMockRecorder) CreateApplicationAssignment(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApplicationAssignment", reflect.TypeOf((*MockISignupRepo)(nil).CreateApplicationAssignment), arg0)
}

// CreateApplicationHistory mocks base method.
func (m *MockISignupRepo) CreateApplicationHistory(arg0 acl.ApplicationHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApplicationHistory", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateApplicationHistory indicates an expected call of CreateApplicationHistory.
func (mr *MockISignupRepoMockRecorder) CreateApplicationHistory(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApplicationHistory", reflect.TypeOf((*MockISignupRepo)(nil).CreateApplicationHistory), arg0)
}

// CreateUserGroup mocks base method.
func (m *MockISignupRepo) CreateUserGroup(arg0 acl.UserGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserGroup", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserGroup indicates an expected call of CreateUserGroup.
func (mr *MockISignupRepoMockRecorder) CreateUserGroup(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserGroup", reflect.TypeOf((*MockISignupRepo)(nil).CreateUserGroup), arg0)
}

// CreateUserPending mocks base method.
func (m *MockISignupRepo) CreateUserPending(arg0 acl.UserPending) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserPending", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserPending indicates an expected call of CreateUserPending.
func (mr *MockISignupRepoMockRecorder) CreateUserPending(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserPending", reflect.TypeOf((*MockISignupRepo)(nil).CreateUserPending), arg0)
}

// GetAdminUserIDsByGroupID mocks base method.
func (m *MockISignupRepo) GetAdminUserIDsByGroupID(arg0 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminUserIDsByGroupID", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminUserIDsByGroupID indicates an expected call of GetAdminUserIDsByGroupID.
func (mr *MockISignupRepoMockRecorder) GetAdminUserIDsByGroupID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminUserIDsByGroupID", reflect.TypeOf((*MockISignupRepo)(nil).GetAdminUserIDsByGroupID), arg0)
}

// GetGroupByName mocks base method.
func (m *MockISignupRepo) GetGroupByName(arg0 string) (acl.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByName", arg0)
	ret0, _ := ret[0].(acl.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByName indicates an expected call of GetGroupByName.
func (mr *MockISignupRepoMockRecorder) GetGroupByName(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByName", reflect.TypeOf((*MockISignupRepo)(nil).GetGroupByName), arg0)
}

// GetUserByID mocks base method.
func (m *MockISignupRepo) GetUserByID(arg0 string) (acl.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", arg0)
	ret0, _ := ret[0].(acl.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockISignupRepoMockRecorder) GetUserByID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockISignupRepo)(nil).GetUserByID), arg0)
}

// ListUserGroupsByGroupID mocks base method.
func (m *MockISignupRepo) ListUserGroupsByGroupID(arg0 string, arg1 int) ([]acl.UserGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserGroupsByGroupID", arg0, arg1)
	ret0, _ := ret[0].([]acl.UserGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserGroupsByGroupID indicates an expected call of ListUserGroupsByGroupID.
func (mr *MockISignupRepoMockRecorder) ListUserGroupsByGroupID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserGroupsByGroupID", reflect.TypeOf((*MockISignupRepo)(nil).ListUserGroupsByGroupID), arg0, arg1)
}
